---
title: "ANLY 530 Group Assignment (Laboratory 2)"
author:
- "Josseline Betio"
- "Akpany Benjamin Ebby"
- "Yajun Wang"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    highlight: zenburn
comment: Rmd Document with Markdown + Embedded R Code
---

---

#### Document as of `r Sys.Date()`

```{r setup, include=FALSE, purl=FALSE, eval=TRUE}

source('R/ANLY530_Laboratory2_Helper.R')

```

```{r echo=FALSE}

library(knitr)
library(kableExtra)
read_chunk('R/ANLY530_Laboratory2_Chunks.R')

```

Some helper functions do exists to support the code snippets below such as: ```fullFilePath```

---

```{r loadLibraries, echo=FALSE, message=FALSE, warning=FALSE}
```

Let us start by [Loading the Data Sheets]

```{r loadSheets, echo=FALSE, message=FALSE, warning=FALSE}
```

# Part 1: Exploring and Preparing the Data

## Collecting the data

```{r collectingData, echo=FALSE, message=FALSE, warning=FALSE}
```

## Step 1

```{r part1Step1, message=FALSE, warning=FALSE}
```

## Step 2: Training a Model on the Data

```{r part1Step2, message=FALSE, warning=FALSE}
```

## Step 3: Evaluating Model Performance

```{r part1Step3, message=FALSE, warning=FALSE}
```
